### ISSUE TITLE
Building cryptominisat on Fedora 26 fails

### ISSUE THREAD

**Issue by baston007** [msoos/cryptominisat#402]
I have just upgrade my PC to Fedora 26 from Fedora 25.  I have deleted the old build directory and remake it, followed by cmake then make.  This is the normal procedure.  Within scalmc.cpp the call to overloaded abs is ambiguous.  I have attached the error message generated to help sort out what "ambiguous" means here.  The gcc compiler has been updated in Fedora 26, so maybe it's catching a previously undetected problem.

Rob

[F26_build_fail.txt](https://github.com/msoos/cryptominisat/files/1143533/F26_build_fail.txt)

**Comment by baston007** [comment]
Update:  The first time I ran make I ran "make -j8".  This generated an error but the build continued.  The second time, I ran "make" without the "-j8".  The above message was generated in the second run.  I see in the build directory there is a "cryptominisat5" and "cryptominisat5_simple".  These must have been compiled during the first run.  So the error must be after these are build.

**Comment by baston007** [comment]
Oops. I think I closed this issue, by mistake.  It's still very much open.

**Comment by baston007** [comment]
Update again:  The version of "cryptominisat5" that was generated appears to work correctly, so something else was not generated.

**Comment by msoos** [comment]
Thanks! Should be fixed :)

**Comment by baston007** [comment]
Not fixed yet.  I just downloaded the latest version, removed the build directory, remake it, reran cmake, then make.  The following attached file shows the error messages generated.
Rob

[F26_build_fail_try2.txt](https://github.com/msoos/cryptominisat/files/1149771/F26_build_fail_try2.txt)

**Comment by msoos** [comment]
Ahhhh!! Good catch! Fixed now I think :)

**Comment by baston007** [comment]
Fixed and looking good.
