### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by a1880** [msoos/cryptominisat#692]
Hi Mate,
The Windows build appears to be broken. VC++ 2015 does not know std::variant.
It took me quite a few tweaks to get CMS 5.11.2 built with VC++ 2022.
[cryptominisat5.11.2_20220928.exe.zip](https://github.com/msoos/cryptominisat/files/9669030/cryptominisat5.11.2_20220928.exe.zip)

Greetings!

Axel

**Comment by msoos** [comment]
Thaaaanks! I just uploaded your binary, and I also fixed the system so it no longer uses `std::variant`. Sorry, I didn't know it will be painful :S

Thanks again,

Mate

**Comment by a1880** [comment]
Sorry that I still can't create proper pull requests.

The following definitions might be helpful:


```
#pragma once
//
//  global.h  -  global forced include for MS VC++ port
//
//  Axel Kemper  27-Sep-2022
//

#if _MSC_VER
#define _CRT_SECURE_NO_WARNINGS
#define _SCL_SECURE_NO_WARNINGS

#include <intrin.h>
#include "stdint.h"

#define UINT32_MAX _UI32_MAX
#define UINT64_MAX _UI64_MAX

#if !defined(INTMAX_MAX)
#define INTMAX_MAX _I32_MAX
#endif

#ifdef _WIN64 // [
#  define PTRDIFF_MIN  _I64_MIN
#  define PTRDIFF_MAX  _I64_MAX
#else  // _WIN64 ][
#  define PTRDIFF_MIN  _I32_MIN
#  define PTRDIFF_MAX  _I32_MAX
#endif  // _WIN64 ]

#pragma warning(disable : 4244)  //  C4244 : 'Argument': Konvertierung von 'const uint64_t' in 'double', möglicher Datenverlust
#pragma warning(disable : 4267)  //  C4267 : 'return': Konvertierung von 'size_t' nach 'uint32_t', Datenverlust möglich
#pragma warning(disable : 4302)  //  C4302 : truncation
#pragma warning(disable : 4305)  //  C4302 : truncation double to float
#pragma warning(disable : 4311)  //  C4311 : pointer truncation
#pragma warning(disable : 4312)  //  C4312 : conversion from .. of greater size
#pragma warning(disable : 4789)  //  C4789 : buffer '' of size xx bytes will be overrun; 

#pragma warning(disable : 4800)  //  C4800 : 'const uint32_t' : Variable wird auf booleschen Wert('True' oder 'False') gesetzt(Auswirkungen auf Leistungsverhalten möglich)
#pragma warning(disable : 4805)  //  C4805 : '==' : unsichere Kombination von Typ 'unsigned short' mit Typ 'bool' in einer Operation
#pragma warning(disable : 4996)  //  C4996 : deprecated
#pragma warning(disable : 26495)  // Always initialize a member variable
#pragma warning(disable : 26819)  //	Unannotated fallthrough between switch labels



#if !defined(__PRETTY_FUNCTION__) && !defined(__GNUC__)
#define __PRETTY_FUNCTION__ __FUNCSIG__
#endif

//  https://gist.github.com/pps83/3210a2f980fd02bb2ba2e5a1fc4a2ef0
//  int __builtin_clzll(unsigned long long x) {
#define __builtin_clzll(x) (int)__lzcnt64(x)

//  https://gist.github.com/pps83/3210a2f980fd02bb2ba2e5a1fc4a2ef0
static inline int __builtin_ctzll(unsigned long long x) {
	unsigned long ret;
	_BitScanForward64(&ret, x);
	return (int)ret;
}

//  https://clickhouse.com/codebrowser/ClickHouse/contrib/croaring/include/roaring/portability.h.html
static inline int __builtin_popcountll(unsigned long long input_num) {
	const uint64_t m1 = 0x5555555555555555; //binary: 0101...
	const uint64_t m2 = 0x3333333333333333; //binary: 00110011..
	const uint64_t m4 = 0x0f0f0f0f0f0f0f0f; //binary:  4 zeros,  4 ones ...
	const uint64_t h01 = 0x0101010101010101; //the sum of 256 to the power of 0,1,2,3...
	input_num -= (input_num >> 1) & m1;
	input_num = (input_num & m2) + ((input_num >> 2) & m2);
	input_num = (input_num + (input_num >> 4)) & m4;
	return (input_num * h01) >> 56;
}

#define NO_DRUP 1
#define NO_USE_ZLIB 1
#define USE_OPENMP 1
#define NO_USE_GAUSS 1
#define NO_STATS_NEEDED 1
#define NO_USE_MYSQL 1

#define NO_DLL_EXPORT 1

#define HAVE_OPENMP 1

#define USE_M4RI 1

//  picosat
#define isatty(x) _isatty(x)
#define NO_USE_GZ  1
#define NO_USE_PIPES 1
#define NGETRUSAGE 1
#define NALLSIGNALS 1

#endif


```

**Comment by msoos** [comment]
Oh wow, that's actually really useful. OK, thanks, let me try to incorporate that!

**Comment by msoos** [comment]
I tried adding your file as per 3d9f5cd993c09a22e1687f9b9f10b5a41bc29dee, let me know if it helps! Thanks again,

Mate

**Comment by a1880** [comment]
The build runs into some errors near the end:

```
c:\projects\cryptominisat\src\cms_windows_includes.h(79): error C2556: 'int _mm_popcnt_u64(unsigned __int64)': overloaded function differs only by return type from '__int64 _mm_popcnt_u64(unsigned __int64)' [C:\projects\cryptominisat\build\cmsat5-src\cryptominisat5.vcxproj]
  c:\projects\cryptominisat\src\cms_windows_includes.h(79): error C2371: '_mm_popcnt_u64': redefinition; different basic types [C:\projects\cryptominisat\build\cmsat5-src\cryptominisat5.vcxproj]
  c:\projects\cryptominisat\src\cms_windows_includes.h(79): error C2169: '_mm_popcnt_u64': intrinsic function, cannot be defined [C:\projects\cryptominisat\build\cmsat5-src\cryptominisat5.vcxproj]
  c:\projects\cryptominisat\src\packedrow.h(146): error C2065: '_mm_popcnt_u64': undeclared identifier [C:\projects\cryptominisat\build\cmsat5-src\cryptominisat5.vcxproj]
  c:\projects\cryptominisat\src\packedrow.h(146): error C2568: '+=': unable to resolve function overload [C:\projects\cryptominisat\build\cmsat5-src\cryptominisat5.vcxproj]
  c:\projects\cryptominisat\src\packedrow.h(320): error C2065: '_mm_popcnt_u64': undeclared identifier [C:\projects\cryptominisat\build\cmsat5-src\cryptominisat5.vcxproj]
  c:\projects\cryptominisat\src\packedrow.h(320): error C2568: '+=': unable to resolve function overload [C:\projects\cryptominisat\build\cmsat5-src\cryptominisat5.vcxproj]
  c:\projects\cryptominisat\src\packedrow.h(329): error C2065: '_mm_popcnt_u64': undeclared identifier [C:\projects\cryptominisat\build\cmsat5-src\cryptominisat5.vcxproj]
  c:\projects\cryptominisat\src\packedrow.h(329): error C2568: '+=': unable to resolve function overload [C:\projects\cryptominisat\build\cmsat5-src\cryptominisat5.vcxproj]
  c:\projects\cryptominisat\src\oracle\bitset.hpp(251): error C3861: '__builtin_ctzll': identifier not found [C:\projects\cryptominisat\build\cmsat5-src\cryptominisat5.vcxproj]
  c:\projects\cryptominisat\src\oracle\bitset.hpp(260): error C3861: '__builtin_popcountll': identifier not found [C:\projects\cryptominisat\build\cmsat5-src\cryptominisat5.vcxproj]
  c:\projects\cryptominisat\src\oracle\bitset.hpp(273): error C3861: '__builtin_popcountll': identifier not found [C:\projects\cryptominisat\build\cmsat5-src\cryptominisat5.vcxproj]
  c:\projects\cryptominisat\src\oracle\bitset.hpp(280): error C3861: '__builtin_ctzll': identifier not found [C:\projects\cryptominisat\build\cmsat5-src\cryptominisat5.vcxproj]
  c:\projects\cryptominisat\src\oracle\bitset.hpp(307): error C3861: '__builtin_ctzll': identifier not found [C:\projects\cryptominisat\build\cmsat5-src\cryptominisat5.vcxproj]

```
